### ISSUE TITLE
error: namespace "thrust" has no member "min_element" during the "Compile fast searching module" step

### ISSUE THREAD

**Issue by shenrsc** [tccoin/image-based-indoor-localization#2]
![complie_error and version of gcc and cuda](https://user-images.githubusercontent.com/112876459/224025810-2ce67e93-a9fe-48ba-89a6-960fa3a464f2.png)
 I met an issues described in attached picture during the step "Compile fast searching module". My gcc and cuda version are shown in the picture as well. I changed cmakelist.txt a little bit(change 20 to 14) because there is an error "invalid value 20". Could you help me to find the problem?

**Comment by tccoin** [comment]
Does the fix mentioned in https://github.com/poweic/libdnn/issues/24#issuecomment-86878210 help?

**Comment by shenrsc** [comment]
Thank you, this issue is fixed. However I met a new one and I will post another issue
